spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cook?characterEncoding=utf-8
    username: root
    password: 19960118

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    password:
    timeout: 0

  session:
    store-type: redis
  cache:
    type: redis
#ElasticSearch
#服务地址
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9301
#      repositories:
#        enabled: true
      #开启仓库


#mybatis配置
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  check-config-location: true
  #mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.sunsharing.kaohe.pojo.Menu

logging:
  level: debug
  pattern:
    console: '%d - %msg%n'







